# Generated by Django 5.2.3 on 2025-10-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('firstName', models.CharField(max_length=64)),
                ('lastName', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('userRole', models.CharField(choices=[('REQUESTER', 'Requester'), ('VOLUNTEER', 'Volunteer')], default='REQUESTER', max_length=32)),
            ],
        ),
    ]
